---
version: "2"
services:
  mongodb:
    image: "registry.hub.docker.com/library/mongo"
    restart: "no"
    networks:
    - "internal"
  golang:
    build: ./
    restart: "no"
    ports:
      - 3000:3000
    environment:
      - APP_DB_HOSTNAME=mongodb
      - APP_PORT=3000
    networks:
    - "internal"
    depends_on: 
    - mongodb
networks:
  internal:
    external: false